language: node_js

node_js:
  - 'iojs'

addons:
  sauce_connect: true

env:
  global:
    - secure: wQi/MHN8/yhYfoub4facJux91apTX8Ke8lDFmJUulmYQ7h3dVczQE2JK+tU49od6M3a1MfeYaDn1PBsOvRId4NUSMUG86CRgtjPIDUIynyRYIu7g+L1hrEETYGBeqCoG0d1CKN2Oka/TzOkQ0oN+nXW9dIo5AehLpsIt2lWpaGiYMqRJDKaceczkobUW0kHRg7SyRGHheZI5x3lfTHAeyZNg6ToUa4g4Nj+ODRbJ8ox5aSV4JMceGk+fOyIJx/hEu/UsNeIzk+38FoVftpUJeHwS+r0M53mu+fwmkrXxkZ6AkJojCPvPRqi16hYRrLlA3cajaWgO4UJxc5nod0us8efh4ULjco2AFhG64Xpvg5q2HTPnj9s0w0vT6rwqBq7bhUPxL996P3e5Giss5He9wpAFYAY1FhOsvLgmz+nezyPjdLhTyS2KPELP5RBGbw0yloPBil+iVwVg5cPkuTwE7klB2BnlIlPX783Y4gFLxDhuofaIv9vMYrRsj/kfo6OwsIidzsI6ysaxjbopyG3dNaO2nDhEIUBSFOlgH59Gd5Za+kLIof8WOA1nnGp2omxpnpWWKEHzjs3pWMnGRod5E6JXhh44gEi7lRensyLlbAmuLsFz38E4gc4pZBwJauTfgKi7dqGZi9Pfkr4dnNY1v2Pal9Q7S/SJdAPQck33XxA=
    - secure: 8L6xmncZTWAsAZZkKq2rO2vm5VJz9PweSoTNM+UQZNGlXPZWcQy5R2I6hGzyGz7iSWOdlAsN9VXqYgrU49slVfucB/3ea8D103HAWT5iQOfBtycieL9SdiBz+kWpxGOwEjcDuqjg2avz7pY588rzVooqAguZrmxqXGhMJjVNvtHe73LfSKaZ1xwQsYjQyDCU8ib/vQnic0Fuq0pkqEWPymvJYnRqpu6n/qHXo9ebfsXtE3N22Dv/JhJHlmYovkYnO8CYQqvTjEHIMY8wUBlVjgG5/pt9V3xRuj4579xPWDSpB8C7AcNNDp0HokwjOp6hu+A9S+t5E0Y0PwMAi5xJCJrPEffP7ZECTvD2OIWYgvJp+7xlknWv68aXugGmvXS/j60OxsRxenerDS50vT3paJHiJXzEbiAQEY9R6e0TasioWCq6KCnzxNsjg17F3saP4Bca6hWuDpgIqLmATnJx8Lcgoxu0fqWJ74tKelxL0WfONb2h+jrDYX7BO5QwEwW+4l5FeMjFk64ixlc0Y7lpC4imNRA6y2pRT4y0HuBz/EQwZ71K/kqHSFuEWpm4q4yva1MhoOPfR1fnZwfXbL1IbNQbLp/ZKrNHiCIPr46I8vblIdsCfajvnsafKuu5xXlZDq8mc4HlRF0WecpEBV1jxujokFjGLwwDPjBIvGHE/dM=
