language: node_js

node_js:
  - 'iojs'

script: make travis

env:
  global:
    - secure: ddh9bETXFuEZr/rY0MKC0UN1xjbs6ub9m4vD4Mnj5b5eRiVZZdW3/81XOUmquLbZDwpuJ1myM7coH3u91KVCVdKQGSKyyufQ6y+QKup+vMfq4HdnbVMNgN+YXqVNFXYGwkjvnjNvcfQ0K+WjMfAo7FG9CdzPR7q5vi69CoAqa1PWXZzBWzm6vvdropUi4KA0Qczb8t9BaAhKZXGRcg4UVLAZXzYmp8HKtEZd+xcsybUBJFmBGgYFwT2OD/xvaJ3imNzEvi9qGHVkXneVAl4dKoQ/5kWdokCWCng9Fb+BvsBoU8RsA6x0Fo8JvuodP7d/52G26CtprN19pRJ5RbeBnlf5Em0n5wuFiM7l3r2RuVCZjUTJHwUNx7p+A9AhEAQub1S0fyIh3oSJDvP356UeLzftV4HsmP4TITGb26Tplf1vSTym0wrgg1MixoriNKfLT9o949dU83Tbw4Vuw480XCmk6+BNAEvOnpV4NPQlbfN2z/A4Pz3SfMooxV3Cn/ssHumtUOKHkoaP0dFk5vbUbumIjrUKwTFOHcYvSrjhM6YgjmjtFeihem2m3tlStynuF0/8zzn3wBiR4KoswJ6SYlklIEHmJz6I75xMz66YUbdRwLCUGHrUZRsGz4opT5gEdKV6Yti7KDpD/oMtypN4hfDrAMzke2sMU6ulekHD1Fo=
    - secure: 58IvmQe4P1DQpD+wiqQl9LZuc+Cqa5Qndp+DXdeTQTPaV8qyW5duBlTzb9z+fNKtVsEPZ+8PAhATGEvmziktn5ymDWlJxK160KOQDVTkggNyLjmxynINBUEPjemInZ0Aat1pKt6Yg3Iu4tuHkB9KXsGF8a3QziBdAlxDO+BYGnwnvaHoCqEXoRKO9VCnaFsoQXMtN1BQlGif0Ca0liy7q3taJAleSrKlHkRIoMsiPrbNFV1a50LsdEJEkVNe+UNt7heDjaS2lnR4kB9GqpySJUfPigbNOoi1VIQSh0/yMBlihO+e4nfHnXPrBaOl9VYEwBfFmVNdKi8Qrx2YotRYiY26XQo8oR6eFYa2EahT8VKe8LQZRevQnfShgZvEqbD2WukBWc9qIFc4gK7L9in/h1xU3ucaqNIN8NIlLWvDhEvy0FORxkAUCVUVIL70QSeM6HHGE2mAIV8wqW2tB8Pfm1aqDUgJeP46M3AOAZbs45MPMyhqGnRArHcfCfW0mEy0Sq4Ojweq4gzAoMaFiI/5UGZKIsiYYTD0+y6EWrHnB9Br5PHSDRgx4KP8NhsWFIgkjn7rc8jP4/M5krEYFrYH++9B5B8ZvGfJk5SWksyU5V5sVeXGZLWdCGorZ1EZyPZiWuEYfNBbN9qZW5LLQA1boQ+2RWOnNpR4QRovD4gWC2k=

